title: Footprints of Sunshine and Moonlight
description: >-
  This project is an effort to compare the different literary footprints present
  in the film Moonlight (2016) and the novel _Stilstville_ (2010). 
social_link: 
social_username: 
github_repo: 
github_username: eugestumm
theme_color: light
remote_theme: internet-de-france/athena
baseurl: /footprints_of_sunshine_and_moonlight
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - light
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
